name: Tweet Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *' # Runs every day at 14:00 UTC

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm install

      - name: Install dotenv manually
        run: npm install dotenv

      - name: Run the tweet release script
        run: node .github/scripts/tweet-release.js
