name: Tweet Macro Calendar

on:
  schedule:
    - cron: '0 12 * * *'  # Adjust your timing if needed
  workflow_dispatch:     # Allow manual runs

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Twitter posting script
        run: node scripts/postToTwitter.js