name: Send Weekly Email

on:
  schedule:
    - cron: '0 9 * * 5'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@3 papaparse

      - name: Run email script
        run: node .github/scripts/send-email.js
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}